### profiles(?)
######### meta
info:
  app:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    packaging: '@project.packaging@'
    description: '@project.description@'
    version: '@project.version@'
    properties:
      java:
        version: '@java.version@'
logging:
  level:
    org:
      springframework:
        kafka: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  kafka:
    broker:
      id: 1
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: adm-service
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      missing-topics-fatal: false
      plain-text: PLAINTEXT://0.0.0.0:9092

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/admservice
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  #datasource:
   # url: jdbc:h2:mem:admservice
    #username: sa
    #password:
    #driverClassName: org.h2.Driver

  #h2:
   # console:
    #  path: /h2-console
     # enabled: true

  sql:
    init:
      mode: never

server:
  error:
    include-message: always
